### PR TITLE
Feature/save and load

### LINKED ISSUE #5: Make state persist navigation and reload
The app should not clear data (remove cards) upon refresh or navigating to a different page and back.
The state could possibly e saved in `local`- or `sessionStorage` or as `cookies`. We might need to think of serialization to reduce stoarge amounts.

This issue might go hand in hand with #6

### PR DESCRIPTION
**Pull request by lennczar**
closes #5

### CODE REVIEW

**Comment by mohamedalichelbi** [comment]
Btw, there's [this](https://github.com/near-multicall/ui/pull/111#issuecomment-1150398513) TODO from the old PR. I think it makes sense as it allows people to copy JSON from proposal arguments or explorer and visualize it on the UI.

**Comment by lennczar** [comment]
Bug:
- drag in card
- go to dao page and back to app page
- card is now linked with menu card

**Comment by mohamedalichelbi** [comment]
bug with custom cards:
1. Drag first custom card.
2. Fill all info correctly in.
3. Switch to DAO page & back to app page.
4. See custom card still has all info correctly filled, BUT the card is marked in red.
5. Keep 1st card and drag 2nd custom card in.
6. Fill all info correctly on 2nd card.
7. switch to DAO page & back to app page.
8. See how 2nd card is empty now.
9. Switch to DAO page & back to app page.
10. See 2nd card has all the info back.

**Comment by mohamedalichelbi** [comment]
Great job! Let's go 🚀

**Pull request merged**
